config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :municipes do
    get 'show_address', action: :show_address, controller: 'municipes'
    resources :addresses
  end

  root 'municipes#index'
  mount LetterOpenerWeb::Engine, at: '/inbox'
end

app/models/address.rb
# frozen_string_literal: true

class Address < ApplicationRecord
  belongs_to :municipe

  validates :postal_code, :address, :neighborhood, :city, :state, presence: true
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/municipe.rb
# frozen_string_literal: true

class Municipe < ApplicationRecord

  include Cns

  has_many :address, dependent: :destroy

  include ImageUploader::Attachment(:image)
  validates :name, :cpf, :cns, :email, :birthday, :phone_country, :phone_area, :phone_number, :image, presence: true

  validates_email_format_of :email, disposable: true
  validates_cpf_format_of :cpf

  validate :email_valid?, :cns_valid?

  after_create :send_sms
  after_update :send_sms

  def email_valid?
    return errors.add(:email, 'inválido') unless email =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  end

  def cns_valid?
    return errors.add(:cns, 'inválido') unless Cns.validate(cns)
  end

  def send_sms
    account_sid = 'ACf1d64e97b71429004e32736adca67d66'
    auth_token = '61d27f26234182919f6121a1dddedf5c'
    client = Twilio::REST::Client.new(account_sid, auth_token)

    # phone_complete = '+' + phone_country.to_s + phone_area.to_s + phone_number.to_s
    # contas trial só podem enviar sms para números previamente cadastrados

    phone_complete = '+5562996334685'
    from = '+12524604039'
    to = phone_complete

    client.messages.create(
      from: from,
      to: to,
      body: "Conta salva!"
    )
  end
end

app/controllers/addresses_controller.rb
# frozen_string_literal: true

class AddressesController < ApplicationController
  before_action :set_municipe
  before_action :set_address, only: %i[show edit update destroy]

  def index
    @addresses = @municipe.address
  end

  def show; end

  def new
    @address = @municipe.address.new
  end

  def edit; end

  def create
    @address = @municipe.address.new(address_params)

    respond_to do |format|
      if @address.save
        format.html { redirect_to municipes_url, notice: 'Endereço criado com sucesso.' }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @address.errors, status: :unprocessable_entity }
        format.turbo_stream { render :form_update, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to municipes_url, notice: 'Endereço editado com sucesso.' }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @address.destroy

    respond_to do |format|
      format.html { redirect_to municipe_addresses_path(@municipe), notice: 'Endereço excluído com sucesso.' }
      format.json { head :no_content }
    end
  end

  private

  def set_municipe
    @municipe = Municipe.find(params[:municipe_id])
  end

  def set_address
    @address = @municipe.address.find(params[:id])
  end

  def address_params
    params.require(:address).permit(:postal_code, :address, :address_complement, :neighborhood, :city, :state,
                                    :ibge_code, :municipe_id)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/municipes_controller.rb
# frozen_string_literal: true

class MunicipesController < ApplicationController
  before_action :set_municipe, only: %i[show edit update]

  def index
    @municipes = Municipe.all.order('created_at DESC')
  end

  def show; end

  def show_address
    @municipe = Municipe.find_by_id(params[:municipe_id])
    @address = Address.find_by_municipe_id(@municipe)
  end

  def new
    @municipe = Municipe.new
  end

  def edit; end

  def create

    @municipe = Municipe.new(municipe_params)

    respond_to do |format|
      if @municipe.save
        to_email = params[:municipe][:email]
        UserMailer.new_municipe(to_email).deliver_now
        format.html { redirect_to municipes_url, notice: 'Cadastro realizado com sucesso.' }
        format.json { render :show, status: :created, location: @municipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @municipe.errors, status: :unprocessable_entity }
        format.turbo_stream { render :form_update, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @municipe.update(municipe_params)
        to_email = params[:municipe][:email]
        UserMailer.update_municipe(to_email).deliver_now
        format.html { redirect_to municipe_url(@municipe), notice: 'Cadastro atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @municipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @municipe.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_municipe
    @municipe = Municipe.find(params[:id])
  end

  def municipe_params
    params[:municipe][:cpf].gsub!(/\D/, "").to_i
    params[:municipe][:cns].gsub!(/\D/, "").to_i
    params[:municipe][:phone_country].gsub!(/\D/, "").to_i
    params[:municipe][:phone_area].gsub!(/\D/, "").to_i
    params[:municipe][:phone_number].gsub!(/\D/, "").to_i
    params.require(:municipe).permit(:name, :cpf, :cns, :email, :birthday, :phone_country, :phone_area,
                                     :phone_number, :image, :status)
  end
end

app/helpers/addresses_helper.rb
# frozen_string_literal: true

module AddressesHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/dashboard_helper.rb
# frozen_string_literal: true

module DashboardHelper
end

app/helpers/municipes_helper.rb
# frozen_string_literal: true

module MunicipesHelper
end

app/views/addresses/_address.html.erb
<h1>Municipe: <%= @municipe.name %></h1>

<h3>Detalhes do Endereço</h3>

<div id="<%= dom_id address %>">
  <p>
    <strong>CEP:</strong>
    <%= address.postal_code %>
  </p>

  <p>
    <strong>Endereço:</strong>
    <%= address.address %>
  </p>

  <p>
    <strong>Complemento:</strong>
    <%= address.address_complement %>
  </p>

  <p>
    <strong>Bairro:</strong>
    <%= address.neighborhood %>
  </p>

  <p>
    <strong>Cidade:</strong>
    <%= address.city %>
  </p>

  <p>
    <strong>Estado:</strong>
    <%= address.state %>
  </p>

  <p>
    <strong>Código IBGE:</strong>
    <%= address.ibge_code %>
  </p>

</div>

app/views/addresses/_form.html.erb
<%= form_with(model: [@municipe, address], :class => "row g-3", local: true) do |form| %>
  <% if address.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(address.errors.count, "error") %> impediram endereço de ser salvo:</h2>

      <ul>
        <% address.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-md-4">
    <%= form.label :postal_code, 'CEP *', { class: "form-label"} %>
    <%= form.text_field :postal_code, class: "form-control", onkeypress:"$(this).mask('00000-000')", :required => true %>
  </div>

  <div class="col-md-8">
    <%= form.label :address, 'Endereço *', { class: "form-label"} %>
    <%= form.text_field :address, class: "form-control", :required => true %>
  </div>

  <div class="col-md-6">
    <%= form.label :address_complement, 'Complemento', { class: "form-label"} %>
    <%= form.text_field :address_complement, class: "form-control" %>
  </div>

  <div class="col-md-6">
    <%= form.label :neighborhood, 'Bairro *', { class: "form-label"} %>
    <%= form.text_field :neighborhood, class: "form-control", :required => true %>
  </div>

  <div class="col-md-4">
    <%= form.label :city, 'Cidade *', { class: "form-label"} %>
    <%= form.text_field :city, class: "form-control", :required => true %>
  </div>

  <div class="col-md-4">
    <%= form.label :state, 'Estado *', { class: "form-label"} %>
    <%= form.text_field :state, class: "form-control", :required => true %>
  </div>

  <div class="col-md-4">
    <%= form.label :ibge_code, 'Código IBGE', { class: "form-label"} %>
    <%= form.text_field :ibge_code, class: "form-control" %>
  </div>

  <div class="alert alert-warning mt-4">
    Todos campos com '*' são obrigatórios
  </div>

  <div class="d-grid gap-2">
    <%= form.submit 'Salvar', :class => 'btn btn-primary' %>
  </div>
<% end %>

<script>
$(document).ready(function() {
  $('#address_postal_code').focus();
  $("#address_postal_code").blur(function(){
    var cep = this.value.replace(/[^0-9]/, "");
    if(cep.length != 8){
      return false;
    }
    var url = "https://viacep.com.br/ws/"+cep+"/json/";

    $.getJSON(url, function(dadosRetorno){
      try{
        $("#address_address").val(dadosRetorno.logradouro);
        $("#address_address_complement").val(dadosRetorno.complemento);
        $("#address_neighborhood").val(dadosRetorno.bairro);
        $("#address_city").val(dadosRetorno.localidade);
        $("#address_state").val(dadosRetorno.uf);
        $("#address_ibge_code").val(dadosRetorno.ibge);
      }catch(ex){}
    });
  });
});
</script>

app/views/addresses/_remote_modal.html.erb
<%= turbo_frame_tag "remote_modal" do %>
  <div class="modal fade" id="shareRecipeModal" tabindex="-1" aria-labelledby="newAddressRemoteModalLabel" aria-hidden="true" data-controller="remote-modal" data-action="turbo:before-render@document->remote-modal#hideBeforeRender">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content" id="modal_content">
        <div class="modal-header">
          <h4 class="modal-title" id="newAddressRemoteModalLabel"><%= title %></h4>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Sair"></button>
        </div>
        <div class="modal-body remote_modal_body" id="remote_modal_body">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
<% end %>

<script>
$(document).ready(function() {
  $("#address_postal_code").blur(function(){
    var cep = this.value.replace(/[^0-9]/, "");

    if(cep.length != 8){
      return false;
    }
    var url = "https://viacep.com.br/ws/"+cep+"/json/";

    $.getJSON(url, function(dadosRetorno){
      try{
        $("#address_address").val(dadosRetorno.logradouro);
        $("#address_address_complement").val(dadosRetorno.complemento);
        $("#address_neighborhood").val(dadosRetorno.bairro);
        $("#address_city").val(dadosRetorno.localidade);
        $("#address_state").val(dadosRetorno.uf);
        $("#address_ibge_code").val(dadosRetorno.ibge);
      }catch(ex){}
    });
  });
});
</script>

app/views/addresses/edit.html.erb
<h1>Editar Endereço</h1>

<%= render "form", address: @address %>
<br>
<div>
  <%= link_to "Voltar", municipes_path %>
</div>

app/views/addresses/form_update.turbo_stream.erb
<%= turbo_stream.update "remote_modal_body" do %>
  <%= render "form", address: @address %>
<% end %>

app/views/addresses/index.html.erb
<p style="color: green"><%= notice %></p>

<%= link_to new_municipe_address_path, :class => 'btn btn-primary btn-sm float-end' do %>
  Adicionar Novo Endereço
<% end %>

<h1>Endereços de Municipe:</h1>
<h2><%= link_to municipe_path(@municipe), :class => 'btn-link' do %><%= @municipe.name%><% end %></h2>

<div id="addresses" class="mt-5">
  <table id="datatable" class="table table-hover">
    <thead class="table-dark">
      <tr>
        <th>CEP</th>
        <th>Endereço</th>
        <th>Complemento</th>
        <th>Bairro</th>
        <th>Cidade</th>
        <th>Estado</th>
        <th>Código IBGE</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @addresses.each do |address| %>
        <tr>
          <td><%= address.postal_code %></td>
          <td><%= address.address %></td>
          <td><%= address.address_complement %></td>
          <td><%= address.neighborhood %></td>
          <td><%= address.city %></td>
          <td><%= address.state %></td>
          <td><%= address.ibge_code %></td>
          <td>
            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
              <%= button_to "Excluir", [@municipe, address], method: :delete, :class => 'btn btn-outline-danger btn-sm me-md-2' %>
              <%= link_to "Ver", municipe_address_path(@municipe, address), :class => 'btn btn-outline-primary btn-sm' %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/addresses/new.html.erb
<h1>Novo Endereço</h1>

<%= render "remote_modal", title: "Novo Endereço" do %>
  <%= render "form", address: @address %>
<% end %>

<br>

<div>
  <%#= link_to "Back to addresses", addresses_path %>
</div>

app/views/addresses/show.html.erb
<p style="color: green"><%= notice %></p>
<%= render "remote_modal", title: "Novo Municipe" do %>
<%= render @address %>

<div>
  <%= link_to "Editar Endereço", edit_municipe_address_path(@municipe, @address) %> |
  <%= link_to "Voltar", municipe_addresses_path(@municipe) %>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jedisapp - Teste</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs5/dt-1.12.1/datatables.min.css"/>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/2.2.3/css/buttons.bootstrap5.min.css"/>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/2.2.3/css/buttons.dataTables.min.css"/>
    <%= javascript_importmap_tags %>
    <script src="https://code.jquery.com/jquery-3.7.0.js" integrity="sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.15/jquery.mask.min.js"></script>
    <script type='text/javascript' src="https://rawgit.com/RobinHerbots/jquery.inputmask/3.x/dist/jquery.inputmask.bundle.js"></script>

  </head>

  <body>
    <div class="container-fluid px-5">
      <%= render 'shared/navbar' %>
      <div class="h-100 p-3 bg-body-tertiary border rounded-3">
        <%= yield %>
        <%= turbo_frame_tag "remote_modal", target: "_top" %>
        <%= turbo_frame_tag "remote_modal_address", target: "_top" %>
      </div>
      <%= render 'shared/footer' %>
    </div>
  </body>
</html>

app/views/municipes/_form.html.erb
<%= form_with(model: municipe, :class => "row g-3") do |form| %>
  <% if municipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(municipe.errors.count, "error") %> erros impediram a conclusão do cadastro:</h2>

      <ul>
        <% municipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-md-12">
    <%= form.label :name, 'Nome Completo *', { class: "form-label"} %>
    <%= form.text_field :name, class: "form-control", :required => true %>
  </div>

  <div class="col-md-6">
    <%= form.label :cpf, 'CPF *', { class: "form-label"} %>
    <%= form.text_field :cpf, class: "form-control", minlength:8, maxlength:20, onkeypress:"$(this).mask('000.000.000-AA')", :required => true %>
  </div>

  <div class="col-md-6">
    <%= form.label :cns, 'Número CNS *', { class: "form-label"} %>
    <%= form.text_field :cns, class: "form-control", onkeypress:"$(this).mask('000 0000 0000 0000')", :required => true%>
  </div>

  <div class="col-md-6">
    <%= form.label :email, 'E-mail *', { class: "form-label"} %>
    <%= form.text_field :email , class: "form-control", :required => true %>
  </div>

  <div class="col-md-6">
    <%= form.label :birthday, 'Data de Nascimento *', { class: "form-label"} %>
    <%= form.date_field :birthday, class: "form-control", min: "1950-01-01", max: Time.now, :required => true %>
  </div>

  <div class="col-md-3">
    <%= form.label :phone_country, 'Código País *', { class: "form-label"} %>
    <%= form.text_field :phone_country,  class: "form-control", minlength:2, maxlength:4, onkeypress:"$(this).mask('+00')", :required => true %>
  </div>

  <div class="col-md-3">
    <%= form.label :phone_area, 'DDD *', { class: "form-label"} %>
    <%= form.text_field :phone_area, class: "form-control", minlength:2, maxlength:4, onkeypress:"$(this).mask('(00)')", :required => true %>
  </div>

  <div class="col-md-6">
    <%= form.label :phone_number, 'Número de Telefone *', { class: "form-label"} %>
    <%= form.text_field :phone_number, class: "form-control", minlength:6, maxlength:13, onkeypress:"$(this).mask('00000 0000')", :required => true %>
  </div>

  <div class="col-md-12">
    <%= form.label :image, 'Foto *', { class: "form-label"} %>
    <%= image_tag form.object.image_url(:thumb) if @municipe.image_data %>
    <br/>
    <%= form.hidden_field :image, value: @municipe.image_data %>
    <%= form.file_field :image %>
  </div>
<br/>
  <div class="col-md-12">
    <%= form.label :status, 'Status *', { class: "form-label"} %>

    <div class="form-check form-check">
      <%= form.radio_button :status, true, :class => "form-check-input", checked: true %>
      <%= form.label :status, "Ativo", :class => "form-check-label", value: "true" %>
    </div>
    <div class="form-check form-check">
      <%= form.radio_button :status, false, :class => "form-check-input" %>
      <%= form.label :status, "Inativo", :class => "form-check-label", value: "false" %>
    </div>
  </div>

  <div class="alert alert-warning mt-3">
    Todos campos são obrigatórios
  </div>

  <div class="d-grid gap-2">
    <%= form.submit 'Salvar', :class => 'btn btn-primary' %>
  </div>
<% end %>

<script>
$(document).ready(function() {
  $("#municipe_email").inputmask({
    mask: "*{1,20}[.*{1,20}][.*{1,20}][.*{1,20}]@*{1,20}[.*{2,6}][.*{1,2}]",
    greedy: false,
    onBeforePaste: function (pastedValue, opts) {
      pastedValue = pastedValue.toLowerCase();
      return pastedValue.replace("mailto:", "");
    },
    definitions: {
      '*': {
        validator: "[0-9A-Za-z!#$%&'*+/=?^_`{|}~\-]",
        casing: "lower"
      }
    }
  });
  $('#municipe_name').focus();
});
</script>

app/views/municipes/_municipe.html.erb
<div id="<%= dom_id municipe %>">
  <p>
    <strong>Nome:</strong>
    <%= municipe.name %>
  </p>

  <p>
    <strong>CPF:</strong>
    <span class="cpf_number"><%= municipe.cpf %></span>
  </p>

  <p>
    <strong>CNS:</strong>
    <span class="cns_number"><%= municipe.cns %></span>
  </p>

  <p>
    <strong>Email:</strong>
    <%= municipe.email %>
  </p>

  <p>
    <strong>Data de Nascimento:</strong>
    <%= municipe.birthday.strftime("%d/%m/%Y") %>
  </p>

  <p>
    <strong>Código País:</strong>
    +<%= municipe.phone_country %>
  </p>

  <p>
    <strong>DDD:</strong>
    (<%= municipe.phone_area %>)
  </p>

  <p>
    <strong>Número de Telefone:</strong>
    <span class="phone_number"><%= municipe.phone_number %></span>
  </p>

  <p>
    <strong>Foto:</strong>
    <%= image_tag municipe.image_url(:thumb) %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= municipe.status ? "Ativo" : "Inativo" %>
  </p>

</div>

app/views/municipes/_remote_modal.html.erb
<%= turbo_frame_tag "remote_modal" do %>
  <div class="modal fade" id="shareRecipeModal" tabindex="-1" aria-labelledby="newMunicipeRemoteModalLabel" aria-hidden="true" data-controller="remote-modal" data-action="turbo:before-render@document->remote-modal#hideBeforeRender">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content" id="modal_content">
        <div class="modal-header">
          <h4 class="modal-title" id="newMunicipeRemoteModalLabel"><%= title %></h4>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Sair"></button>
        </div>
        <div class="modal-body remote_modal_body" id="remote_modal_body">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/municipes/_remote_modal_address.html.erb
<%= turbo_frame_tag "remote_modal_address" do %>
  <div class="modal fade" id="shareRecipeModal" tabindex="-1" aria-labelledby="showAddressRemoteModalLabel" aria-hidden="true" data-controller="remote-modal" data-action="turbo:before-render@document->remote-modal#hideBeforeRender">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content" id="modal_content">
        <div class="modal-header">
          <h4 class="modal-title" id="showAddressRemoteModalLabel"><%= title %></h4>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Sair"></button>
        </div>
        <div class="modal-body remote_modal_body" id="remote_modal_body">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/municipes/edit.html.erb
<h1>Editar Municipe</h1>

<%= render "form", municipe: @municipe %>

<br>

<div>
  <%= link_to "Ver Todos", municipes_path %>
</div>

app/views/municipes/form_update.turbo_stream.erb
<%= turbo_stream.update "remote_modal_body" do %>
  <%= render "form", municipe: @municipe %>
<% end %>

app/views/municipes/index.html.erb
<p style="color: green"><%= notice %></p>

<%= link_to new_municipe_path, :class => 'btn btn-primary btn-sm float-end', data: { turbo_frame: "remote_modal" }  do %>
  Criar Novo
<% end %>
<h1>Municipes</h1>

<div id="municipes" class="mt-5 table-responsive">
  <table id="datatable" class="table table-hover">
    <thead class="table-dark">
      <tr>
        <th>Nome</th>
        <th>CPF</th>
        <th>CNS</th>
        <th>E-mail</th>
        <th>Data de Nascimento</th>
        <th>Código País</th>
        <th>DDD</th>
        <th>Telefone</th>
        <th>Status</th>
        <th>Foto</th>
        <th>&nbsp;</th>
      </tr>
    </thead>
    <tbody>
      <% @municipes.each do |municipe| %>
        <tr>
          <td><%= link_to municipe.name, municipe, :class => 'btn btn-link btn-sm' %></td>
          <td><span class="cpf_number"><%= municipe.cpf %></span></td>
          <td><span class="cns_number"><%= municipe.cns %></span></td>
          <td><%= municipe.email %></td>
          <td><%= municipe.birthday.strftime("%d/%m/%Y") %></td>
          <td>+<%= municipe.phone_country %></td>
          <td>(<%= municipe.phone_area %>)</td>
          <td><span class="phone_number"><%= municipe.phone_number %></span></td>
          <td><%= municipe.status ? "Ativo" : "Inativo" %></td>
          <td><%= image_tag municipe.image_url(:thumb), :class => "image" if municipe.image %></td>
          <td>
          <% if !municipe.address.ids.empty? %>
            <%= link_to municipe_show_address_path(municipe), :class => 'btn btn-primary btn-sm float-end', data: { turbo_frame: "remote_modal_address" }  do %>
              Endereço
            <% end %>
          <% else %>
            <%= link_to new_municipe_address_path(municipe), :class => 'btn btn-primary btn-sm float-end', data: { turbo_frame: "remote_modal" }  do %>
              Adicionar Novo Endereço
            <% end %>
          <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<script>
$(document).ready(function() {
  $('.cpf_number').mask('000.000.000-AA');
  $('.cns_number').mask('000 0000 0000 0000');
  $('.phone_number').mask('00000 0000');
});
</script>

app/views/municipes/new.html.erb
<h1>Novo Municipe</h1>

<%= render "remote_modal", title: "Novo Municipe" do %>
  <%= render "form", municipe: @municipe %>
<% end %>
<br>

<div>
  <%= link_to "Ver Todos", municipes_path %>
</div>

app/views/municipes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @municipe %>

<div>
  <%= link_to "Editar", edit_municipe_path(@municipe) %> |
  <%= link_to "Ver Todos", municipes_path %>

</div>

<script>
$(document).ready(function() {
  $('.cpf_number').mask('000.000.000-AA');
  $('.cns_number').mask('000 0000 0000 0000');
  $('.phone_number').mask('00000 0000');
});
</script>

app/views/municipes/show_address.html.erb
<p style="color: green"><%= notice %></p>
<%= render "remote_modal_address", title: "Endereço" do %>
  <%= render @address %>
  <%= link_to "Editar Endereço", edit_municipe_address_path(@municipe, @address) %>
<% end %>

app/views/shared/_footer.html.erb
<footer class="py-3 my-4 bg-body-tertiary border rounded-3">
  <ul class="nav justify-content-center border-bottom pb-3 mb-3">
    <li class="nav-item"><%= link_to 'Home', root_url, :class => 'nav-link px-2 text-body-secondary' %></li>
    <li class="nav-item"><%= link_to 'Emails Enviados', letter_opener_web_path, target: "_blank", :class => 'nav-link px-2 text-body-secondary' %></li>
  </ul>
  <p class="text-center text-body-secondary">© 2023</p>
</footer>

app/views/shared/_navbar.html.erb
<header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
  <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
    <span class="fs-4">Teste Jedis</span>
  </a>

  <ul class="nav nav-pills">
    <li class="nav-item"><a href="/" class="nav-link active" aria-current="page">Início</a></li>
  </ul>
</header>